#!/bin/bash

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi

ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

picom &> /dev/null &

leftwm-command "LoadTheme theme.ron"

feh --bg-scale $SCRIPTPATH/background.jpg

polybar bar &> /dev/null
